---
title: "TEACHING"
about: 
  template: marquee
---

Below you will find a list of courses taught, including the course description. I am currently preparing a course on premodern political theory to be taught at the University of Montreal in Winter 2025. At Deep Springs College, I designed and taught seminars as a visiting professor.  Previously, I had the chance to teach four times for Prof. Michael Sandel at Harvard where, as a teaching fellow, I guided discussion sections and provided short supplementary lectures.

I take pride in challenging students to move beyond their limitations, while giving them the support they need to do so, all in an environment of mutual respect and collaboration.  One of my students stated my goal better than I could: “a subtle but ever-present mixture of high respect for his students in our current form and deep faith in their ability to improve/elevate our thinking.”

## **L'Université de Montréal**

POL2090: *Pensée politique prémoderne* \[Premodern Political Thought: Cities and Stories in the Global Mediterranean\] (L'Université de Montréal), Winter 2025.
```{=html}
<p class="text-left">
  <a class="btn btn-secondary btn-sm" href="https://pol.umontreal.ca/public/FAS/science_politique/Documents/1-PROGRAMMES_ET_COURS/Cours_et_horaires/Hiver_2025/POL2090_H25_Tilleczek.pdf" target="_blank">
    </i>&ensp;Info here
  </a>
```


[Description]{.underline}: As its title implies, this course offers an introduction to ancient political thought - primarily from the Mediterranean and India - with attention to the global context of early human civilizations.  As its subtitle implies, this course will be guided by three major themes: *Souls*, or the question of ethics and the good life; *Cities*, or the *polis* and the question of the political organization of human communities; and *Stories*, or the question of the kinds of things we can say and know about politics, and the language in which people have conveyed this knowledge.  We will pay particular attention to the close connection of the ‘personal’ and the ‘political’ in ancient thought: politics means not only the exercise of power, but the connection between the political regime and the types of people who create it and who are, in turn, created by it.  Attempting as much as possible to shed contemporary disciplinary boundaries, we will see how the political was thought and enacted in domains as diverse as treatises, plays, epic poems, or simply in the daily life of political actors as reported and preserved by ancient biographers.  Why study political thought thousands of years removed from our contemporary reality?  This is a fair question to which I hope all students will be able to provide *their own answer* by the end of the course.  But for all of those who wonder about historical variations in the idea of democracy, the injustice of slavery, the role of story-telling and history in identity-formation, the place of the individual within the nation, the long history of global contacts and imperial violence, the politics of the Self and the Other, or the liberatory role of education, the “modernity” of these ancient texts will quickly become apparent...  Please note that the readings in this course will be mostly (but not exclusively) chronologically presented, and will necessarily be lacunary, as we will cover approximately 1500 years of history in one semester.

## **Deep Springs College**

SOC204: *Hannah Arendt and Simone Weil: Work and Politics* (Deep Springs College), Winter 2023.

[Description]{.underline}: This class brings together two contemporary philosophers and social critics, Simone Weil (1909-1943) and Hannah Arendt (1906-1975), both of whom abhorred the totalitarianisms of their time, reflected on the possibilities of a post-Marxist politics, and theorized the meaning of labour in human life.  Weil, a French mystic, ascetic, activist, and philosopher, was deeply dedicated to understanding working-class life and violence in its many forms.  Arendt, a German-born philosopher (or rather, as she herself preferred, *political theorist*), wrote much of her work in the United States during and after the Second World War and offered a wealth of theoretical tools to understand human labour and work as well as freedom and political action.  Our goal will be a “lecture croisée” of these two *oeuvres* oriented around two major thematics: (1) Forms of human activity and their relation to political life; (2) Marxism and its major nodal points of revolution and freedom.  Along the way we will also think about ancient Greece, the tradition of political thought, colonial violence, and our own neoliberal economic reality.  Readings are a combination of major works from each author (*The Need for Roots* and *The Human Condition*), essays and occasional pieces (e.g. “The Iliad, or the Poem of Force” and “Revolution and Freedom”), as well as contextualizing readings from theorists who inspired or were inspired by Weil and Arendt (Karl Marx, Frantz Fanon, Albert Camus, Danielle Allen).

HUM010: *Introduction to Ancient Greek Language & Literature* (Deep Springs College), Winter 2023.

[Description]{.underline}: This course is intended for students who have completed their initial study of Greek grammar (e.g. by completing an introductory course sequence) and who have some experience reading original (viz., un-adapted) Greek prose.  The transition from textbook study to the engagement with real Greek authors can be a difficult one, and this course aims to facilitate this transition by combining continued reading of a complete Greek text with a rapid but comprehensive review of Attic Greek morpho-syntax.  Our primary goal is to read Plato’s *Gorgias* in its entirety, in order to become familiar with idiomatic Greek and to expand our vocabulary through repeated exposure to Plato’s prose.  Our secondary goal is to revisit challenging elements of Greek grammar through a review of Louise Pratt’s *The Essentials of Greek Grammar* as well as via ad-hoc review of difficult points that arise during our reading.  Class will consist primarily of the close reading of Plato’s text, a specific section of which will be assigned in advance of each class.  Students are expected to work through this text in advance (e.g. look up and record all unknown vocabulary, decipher any challenging syntactic constructions), and be prepared to translate the text with the help of their notes – but without a prepared translation – ‘live’ in class.  We will always read the Greek out loud before translating to gain familiarity with the sounds and the rhythm of the language.  While our main goal is to improve our Greek reading fluency, we will take time to discuss Plato’s views on rhetoric, ethics, and politics as raised in this fascinating Socratic dialogue. 

## **Harvard University**

GENED 1181: *Meritocracy and its Critics*, (Harvard University), Fall 2022.

GENED 1171: *Justice: Ethics in an Age of Pandemic and Racial Reckoning* (Harvard University), Fall 2020 (Assistant Head Teaching Fellow).

GOVT E-1045: *Justice* (Harvard Extension School), Spring 2019

ETHRSON 39: *Money, Markets, and Morals* (Harvard University), Fall 2018. 
